<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <title>Transat</title>
  </head>
  <body>
    <header>
      <!--<h1><a href="homepage.php">Pierrot sur l'eau</a></h1>-->
      <div class="menuglobal">
      <nav>
        <ul>
          <li><a href="homepage.php">Home</a></li>
          <li><a href="transat.php">Transat</a></li>
        </ul>

        <div class="menu">
          <ul>
            <li><a href="homepage.php">Home</a></li>
            <li><a href="budget.php">Budget</a></li>
          </ul>
        </div>
      </nav>
      <!--<img src="photos/header.png" alt="#">-->
      </div>
    </header>
  </body>
</html>
