<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <main class="container">
      <h1>Transat</h1>
      <article>
        <fieldset >
          <legend>Lorem ipsum</legend>

          <div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat voluptates quo incidunt quidem ut error, doloremque libero eveniet numquam tempora deleniti laudantium odit temporibus consequuntur assumenda eligendi porro quibusdam mollitia ea repellendus dolor maiores soluta vero, placeat! Aut ad, culpa explicabo ullam possimus non, excepturi laboriosam iste consectetur quas recusandae!
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat voluptates quo incidunt quidem ut error, doloremque libero eveniet numquam tempora deleniti laudantium odit temporibus consequuntur assumenda eligendi porro quibusdam mollitia ea repellendus dolor maiores soluta vero, placeat! Aut ad, culpa explicabo ullam possimus non, excepturi laboriosam iste consectetur quas recusandae!
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat voluptates quo incidunt quidem ut error, doloremque libero eveniet numquam tempora deleniti laudantium odit temporibus consequuntur assumenda eligendi porro quibusdam mollitia ea repellendus dolor maiores soluta vero, placeat! Aut ad, culpa explicabo ullam possimus non, excepturi laboriosam iste consectetur quas recusandae!
            </p>
          </div>
        </fieldset>
      </article>

      <img class="left" src="photos/transat.png" alt="#">
    </main>


  </body>
</html>
